### ISSUE TITLE
ポップアップの機構を作る

### ISSUE THREAD

**Issue by Mori-Atsushi** [cyder/SyncPod-web-app#22]
## 目的はなんですか
* signin / signup / ルーム入室等に使用する

## どのような方法が考えられますか
* apollo clientで状態を保持する
* mutationでopen / closeできるようにする

**Comment by tanishi** [comment]
無知で申し訳ないんだけど
apollo clientで状態持つと何が嬉しいんだっけ:thinking:

**Comment by Mori-Atsushi** [comment]
いわゆる状態管理をapollo clientで統一しようって流れです…！

**Comment by euglena1215** [comment]
これはやはり一度 @Mori-Atsushi がLTでapollo(GraphQL)の紹介をすべきなのでは...? 🤔

**Comment by Mori-Atsushi** [comment]
apollo詳しくないので @euglena1215 にお譲りします。
