### ISSUE TITLE
共通ヘッダー

### ISSUE THREAD

**Issue by tanishi** [cyder/SyncPod-web-app#26]
## 目的はなんですか

共通ヘッダー作りたいです

<img width="1289" alt="スクリーンショット 2019-04-03 14 35 52" src="https://user-images.githubusercontent.com/13435109/55455264-f8387280-561d-11e9-87b6-5f20c148597d.png">

- 左上のロゴはクリックでトップページに遷移する
- 右のメニューはサインイン状態かによって内容が変化する

## どのような方法が考えられますか
- （一応）atomic designに従う
- emotionを使ってstyleを作る

## 議論はありますか

議論というかめも

- サインイン状態かどうかを引っ張ってきてview側で処理する

okahiさんに聞くリスト
- ヘッダーのアイコン
- ヘッダーのタイトル
    - 画像
    - 文字(フォント)
- ヘッダーのバックグラウンドカラー

**Comment by Mori-Atsushi** [comment]
若干概要追記しました！

**Comment by onishi-ryo** [comment]
感謝！

**Comment by tanishi** [comment]
フォント: 游ゴシック
以下使っているカラーコード
#3B4043
#6F7579
#959EA7
#F0F3F5
#FFFFFF
#FBB143
#F05C00
